### ISSUE TITLE
Почему русский и английский язык не группированы?

### ISSUE THREAD

**Issue by koderhun** [rtivital/react-things#3]
Заметил, в списке нет какой то группировки, вроде сначала идут материалы на русском языке а потом на английском. Это не группировка в случайном порядке или придерживались определенной закономерности. 
Спасибо что собрали столько материалов в одном месте и на русском языке.

**Comment by rtivital** [comment]
Материалы группируются по теме, внутри темы группировки по языку нет, то есть они могут идти в произвольном порядке. Если есть желание, можешь помочь, прислав пулл реквест, и отсортировать материалы, поставив русскоязычные в начало.

**Comment by rtivital** [comment]
Материалы были отсортированы в #5
